-- ============================================
-- MOCKUP DATA FOR SHOPEELIKE (NEW SCHEMA)
-- ============================================
USE shopeelike;

-- Shipping services (ensure at least one)
INSERT INTO shipping_service (carrier, service_name, est_days_min, est_days_max, base_fee, per_kg_fee)
VALUES ('DefaultCarrier', 'Standard', 2, 5, 0, 0)
ON DUPLICATE KEY UPDATE carrier = VALUES(carrier);

-- Categories
INSERT INTO category (name, description)
VALUES 
  ('Electronics', 'Devices and gadgets'),
  ('Fashion', 'Clothing and accessories'),
  ('Home & Living', 'Furniture and decor')
ON DUPLICATE KEY UPDATE description = VALUES(description);

-- Create a seller account and seller profile
-- Password hash for seller1@demo.com (password123), generated by bcryptjs with cost 10
INSERT INTO user_account (email, password_hash, display_name, user_name, phone_number, date_of_birth)
VALUES ('seller1@demo.com', '$2a$10$LEE5v5MMt0tgzp5vta8/zew6BhgDpfIwg7/9fKOEbrtZj8LfeJEkK', 'Tech Store', 'techstore', '+84901111111', '1990-01-01')
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name);

-- Create seller row (auto-generate seller_id via trigger)
INSERT INTO seller (seller_id, user_id, shop_name, tax_id)
VALUES (NULL, (SELECT user_id FROM user_account WHERE email = 'seller1@demo.com'), 'Tech Store', 'TAX123456')
ON DUPLICATE KEY UPDATE tax_id = VALUES(tax_id);

-- Products for the seller
INSERT INTO product (seller_id, title, description, status)
VALUES 
  ((SELECT seller_id FROM seller WHERE shop_name = 'Tech Store'), 'Sample Phone X', 'A modern smartphone', 'Active'),
  ((SELECT seller_id FROM seller WHERE shop_name = 'Tech Store'), 'Lightweight Laptop 13"', 'Portable productivity laptop', 'Active'),
  ((SELECT seller_id FROM seller WHERE shop_name = 'Tech Store'), 'Noise-canceling Headphones', 'Immersive sound experience', 'Active');

-- Map products to categories
INSERT INTO product_category (product_id, category_id)
SELECT p.product_id, c.category_id FROM product p, category c 
WHERE p.title = 'Sample Phone X' AND c.name = 'Electronics'
ON DUPLICATE KEY UPDATE product_category.product_id = product_category.product_id;
INSERT INTO product_category (product_id, category_id)
SELECT p.product_id, c.category_id FROM product p, category c 
WHERE p.title = 'Lightweight Laptop 13"' AND c.name = 'Electronics'
ON DUPLICATE KEY UPDATE product_category.product_id = product_category.product_id;
INSERT INTO product_category (product_id, category_id)
SELECT p.product_id, c.category_id FROM product p, category c 
WHERE p.title = 'Noise-canceling Headphones' AND c.name = 'Electronics'
ON DUPLICATE KEY UPDATE product_category.product_id = product_category.product_id;

-- Variants
INSERT INTO product_variant (product_id, variant_code, sku, list_price, stock_qty, is_active)
SELECT product_id, 'DEFAULT', 'SPX-001', 5990000, 20, TRUE FROM product WHERE title = 'Sample Phone X'
ON DUPLICATE KEY UPDATE list_price = VALUES(list_price), stock_qty = VALUES(stock_qty);
INSERT INTO product_variant (product_id, variant_code, sku, list_price, stock_qty, is_active)
SELECT product_id, 'DEFAULT', 'LL13-001', 18990000, 10, TRUE FROM product WHERE title = 'Lightweight Laptop 13"'
ON DUPLICATE KEY UPDATE list_price = VALUES(list_price), stock_qty = VALUES(stock_qty);
INSERT INTO product_variant (product_id, variant_code, sku, list_price, stock_qty, is_active)
SELECT product_id, 'DEFAULT', 'NCH-001', 2990000, 30, TRUE FROM product WHERE title = 'Noise-canceling Headphones'
ON DUPLICATE KEY UPDATE list_price = VALUES(list_price), stock_qty = VALUES(stock_qty);

-- Images (primary image per product)
INSERT INTO product_image (product_id, url, caption)
SELECT product_id, 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600', 'Sample Phone X' FROM product WHERE title = 'Sample Phone X';
INSERT INTO product_image (product_id, url, caption)
SELECT product_id, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600', 'Lightweight Laptop 13"' FROM product WHERE title = 'Lightweight Laptop 13"';
INSERT INTO product_image (product_id, url, caption)
SELECT product_id, 'https://images.unsplash.com/photo-1518443895914-6b0f0d6f58f2?w=600', 'Noise-canceling Headphones' FROM product WHERE title = 'Noise-canceling Headphones';

-- ============================================================
-- ADDITIONAL DEMO DATA (BUYERS, ADDRESSES, ORDERS)
-- ============================================================

-- Demo buyers (password: password123, same hash as seller)
INSERT INTO user_account (email, password_hash, display_name, user_name, phone_number, date_of_birth)
VALUES
  ('buyer1@demo.com', '$2a$10$LEE5v5MMt0tgzp5vta8/zew6BhgDpfIwg7/9fKOEbrtZj8LfeJEkK', 'Minh Nguyen',  'buyer1', '+84911111111', '1992-02-02'),
  ('buyer2@demo.com', '$2a$10$LEE5v5MMt0tgzp5vta8/zew6BhgDpfIwg7/9fKOEbrtZj8LfeJEkK', 'Lan Tran',     'buyer2', '+84922222222', '1995-03-03'),
  ('buyer3@demo.com', '$2a$10$LEE5v5MMt0tgzp5vta8/zew6BhgDpfIwg7/9fKOEbrtZj8LfeJEkK', 'Quang Le',     'buyer3', '+84933333333', '1990-07-15')
ON DUPLICATE KEY UPDATE display_name = VALUES(display_name);

-- Buyer profiles
INSERT INTO buyer (user_id, loyalty_level)
SELECT user_id, 'Silver' FROM user_account WHERE email = 'buyer1@demo.com'
ON DUPLICATE KEY UPDATE loyalty_level = VALUES(loyalty_level);

INSERT INTO buyer (user_id, loyalty_level)
SELECT user_id, 'Bronze' FROM user_account WHERE email = 'buyer2@demo.com'
ON DUPLICATE KEY UPDATE loyalty_level = VALUES(loyalty_level);

INSERT INTO buyer (user_id, loyalty_level)
SELECT user_id, 'Gold' FROM user_account WHERE email = 'buyer3@demo.com'
ON DUPLICATE KEY UPDATE loyalty_level = VALUES(loyalty_level);

-- Seller default address (warehouse)
SET @seller_id := (SELECT seller_id FROM seller WHERE shop_name = 'Tech Store' LIMIT 1);
INSERT INTO address (seller_id, recipient_name, phone, line1, city, country, is_default)
SELECT @seller_id, 'Tech Store Warehouse', '+84901111111', '456 Vo Van Tan', 'Ho Chi Minh City', 'VN', TRUE
WHERE NOT EXISTS (
  SELECT 1 FROM address WHERE seller_id = @seller_id AND is_default = TRUE
);

-- Buyer default addresses
SET @buyer1_id := (SELECT user_id FROM user_account WHERE email = 'buyer1@demo.com');
SET @buyer2_id := (SELECT user_id FROM user_account WHERE email = 'buyer2@demo.com');
SET @buyer3_id := (SELECT user_id FROM user_account WHERE email = 'buyer3@demo.com');

INSERT INTO address (buyer_id, recipient_name, phone, line1, city, country, postal_code, is_default)
SELECT @buyer1_id, 'Minh Nguyen', '+84911111111', '123 Le Loi', 'Ho Chi Minh City', 'VN', '700000', TRUE
WHERE NOT EXISTS (
  SELECT 1 FROM address WHERE buyer_id = @buyer1_id AND is_default = TRUE
);

INSERT INTO address (buyer_id, recipient_name, phone, line1, city, country, postal_code, is_default)
SELECT @buyer2_id, 'Lan Tran', '+84922222222', '89 Nguyen Hue', 'Ho Chi Minh City', 'VN', '700100', TRUE
WHERE NOT EXISTS (
  SELECT 1 FROM address WHERE buyer_id = @buyer2_id AND is_default = TRUE
);

INSERT INTO address (buyer_id, recipient_name, phone, line1, city, country, postal_code, is_default)
SELECT @buyer3_id, 'Quang Le', '+84933333333', '45 Tran Hung Dao', 'Ha Noi', 'VN', '100000', TRUE
WHERE NOT EXISTS (
  SELECT 1 FROM address WHERE buyer_id = @buyer3_id AND is_default = TRUE
);

-- Demo orders for buyers, using existing products and default variants
SET @service_id := (SELECT service_id FROM shipping_service ORDER BY service_id ASC LIMIT 1);

-- Order 1 for buyer1: 1x Sample Phone X
SET @ship_to1 := (SELECT address_id FROM address WHERE buyer_id = @buyer1_id ORDER BY is_default DESC, address_id ASC LIMIT 1);
SET @ship_from := (SELECT address_id FROM address WHERE seller_id = @seller_id ORDER BY is_default DESC, address_id ASC LIMIT 1);

INSERT INTO orders (buyer_id, ship_to_address_id, ship_from_address_id, service_id, shipping_fee, status, total_amount)
VALUES (@buyer1_id, @ship_to1, @ship_from, @service_id, 0, 'Completed', 0);
SET @order1 := LAST_INSERT_ID();

INSERT INTO order_item (order_id, line_no, product_id, variant_code, qty, unit_price)
SELECT @order1, 1, p.product_id, v.variant_code, 1, v.list_price
FROM product p
JOIN product_variant v ON v.product_id = p.product_id AND v.variant_code = 'DEFAULT'
WHERE p.title = 'Sample Phone X'
LIMIT 1;

-- Order 2 for buyer2: 1x Laptop + 2x Headphones
SET @ship_to2 := (SELECT address_id FROM address WHERE buyer_id = @buyer2_id ORDER BY is_default DESC, address_id ASC LIMIT 1);

INSERT INTO orders (buyer_id, ship_to_address_id, ship_from_address_id, service_id, shipping_fee, status, total_amount)
VALUES (@buyer2_id, @ship_to2, @ship_from, @service_id, 50000, 'Paid', 0);
SET @order2 := LAST_INSERT_ID();

INSERT INTO order_item (order_id, line_no, product_id, variant_code, qty, unit_price)
SELECT @order2, 1, p.product_id, v.variant_code, 1, v.list_price
FROM product p
JOIN product_variant v ON v.product_id = p.product_id AND v.variant_code = 'DEFAULT'
WHERE p.title = 'Lightweight Laptop 13"'
LIMIT 1;

INSERT INTO order_item (order_id, line_no, product_id, variant_code, qty, unit_price)
SELECT @order2, 2, p.product_id, v.variant_code, 2, v.list_price
FROM product p
JOIN product_variant v ON v.product_id = p.product_id AND v.variant_code = 'DEFAULT'
WHERE p.title = 'Noise-canceling Headphones'
LIMIT 1;

-- Order 3 for buyer3: 2x Phone
SET @ship_to3 := (SELECT address_id FROM address WHERE buyer_id = @buyer3_id ORDER BY is_default DESC, address_id ASC LIMIT 1);

INSERT INTO orders (buyer_id, ship_to_address_id, ship_from_address_id, service_id, shipping_fee, status, total_amount)
VALUES (@buyer3_id, @ship_to3, @ship_from, @service_id, 0, 'Shipped', 0);
SET @order3 := LAST_INSERT_ID();

INSERT INTO order_item (order_id, line_no, product_id, variant_code, qty, unit_price)
SELECT @order3, 1, p.product_id, v.variant_code, 2, v.list_price
FROM product p
JOIN product_variant v ON v.product_id = p.product_id AND v.variant_code = 'DEFAULT'
WHERE p.title = 'Sample Phone X'
LIMIT 1;

-- Optional: create demo buyer (password hash same as above). You can also simply register via API instead.
-- INSERT INTO user_account (email, password_hash, display_name, user_name, phone_number, date_of_birth)
-- VALUES ('buyer1@demo.com', '$2a$12$LQv3c1yqBw1uWFlE6qs6Zu5lUyED8VZl5.Q6A9a8BQ4QGCWw8a1nq', 'Minh Nguyen', 'minhnguyen', '+84911111111', '1992-02-02');
-- INSERT INTO buyer (user_id) SELECT user_id FROM user_account WHERE email = 'buyer1@demo.com';

-- You can also prefill a cart for the buyer above if you uncomment it.
-- INSERT INTO cart (buyer_id, status) SELECT user_id, 'Active' FROM user_account WHERE email = 'buyer1@demo.com';
-- INSERT INTO cart_item (cart_id, product_id, variant_code, qty)
-- SELECT (SELECT cart_id FROM cart WHERE buyer_id = (SELECT user_id FROM user_account WHERE email = 'buyer1@demo.com') ORDER BY cart_id DESC LIMIT 1),
--        (SELECT product_id FROM product WHERE title = 'Sample Phone X'), 'DEFAULT', 1;
